name: Run Tests

on: pull_request

jobs:
  run-tests:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
